name: Update GitHub stats

on:
  schedule:
    - cron: "0 4 * * *"
  push:
    paths:
      - ".github/workflows/github-stats.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate stats with metrics action
        uses: lowlighter/metrics@latest
        with:
          filename: stats/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Fazman-s
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          config_twemoji: yes
          plugin_lines: yes
          plugin_notable: yes

      - name: Generate top languages
        uses: lowlighter/metrics@latest
        with:
          filename: stats/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Fazman-s
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./stats/
          git commit -m "Update GitHub stats" || exit 0
          git push
